# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-27 08:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0003_auto_20170526_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='armurl',
            name='shortcode',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
    ]
