# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-02 13:33
from __future__ import unicode_literals

from django.db import migrations, models
import shortener.validators


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0005_auto_20170529_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='armurl',
            name='url',
            field=models.CharField(max_length=220, validators=[shortener.validators.validate_url, shortener.validators.validate_dot_com]),
        ),
    ]
